### ISSUE TITLE
undefined method `migration_context' for an instance of ActiveRecord::ConnectionAdapters::PostGISAdapter (NoMethodError)

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [rgeo/activerecord-postgis-adapter#400]
Hello,
I'm getting NoMethodError: undefined method `migration_context' for an instance of ActiveRecord::ConnectionAdapters::PostGISAdapter (NoMethodError) after upgrading to rails 7.2 beta 2 and using the latest commit in the gem

**Comment by viktorsmari** [comment]
Ran into this also.

Reproduce with `rails console`:
`ActiveRecord::Base.connection.migration_context.needs_migration?`

This works on Rails 7.1, but not on Rails 7.2 with this latest gem in the Gemfile:

`gem 'activerecord-postgis-adapter', github: 'rgeo/activerecord-postgis-adapter'`

**Comment by BuonOmo** [comment]
Yes this gem is not yet compatible with 7.2 non-beta, you can point to the related branch (see #405) or wait, we should release soon.

**Comment by viktorsmari** [comment]
Thanks @BuonOmo just an FYI, now we have in our Gemfile.lock:

```bash
rails 7.2.2
activerecord-postgis-adapter (10.0.0)
rgeo-activerecord (~> 8.0.0)
```

Gemfile:
`gem 'activerecord-postgis-adapter'`

And still have the `undefined method` issue, so our tests fail, but we use the gem in production without issues so far :crossed_fingers:
