### PR TITLE
ActiveRecord 4.2

### PR DESCRIPTION
**Pull request by teeparham**
This branch is released as 3.0.0.beta1. Test with:

```ruby
gem "activerecord-postgis-adapter", "3.0.0.beta1"
```

There are significant changes to the PostgreSQL adapter in ActiveRecord 4.2, and it is extremely cumbersome to support prior versions in a single code base. Therefore, instead of having conditional support for prior versions of ActiveRecord, this adapter will only support ActiveRecord 4.2 and later in the master branch and version 3.0.

`activerecord-postgis-adapter` version 2.x will continue to support ActiveRecord 4.0 and 4.1.

`activerecord-postgis-adapter` version 3.x will support ActiveRecord 4.2 and later.

### CODE REVIEW

**Comment by teeparham** [comment]
I think I've identified the source of many problems: AR 4.2's Postgres adapter supports the Postgres native "point" type, which conflicts with the "point" type defined by `activerecord-postgis-adapter`. The solution is likely to rename the point type for this adapter, likely to `geo_point`.

**Comment by KillaPL** [comment]
I used gem from source you provided and I'm finding some issues. Up to this point, I had:

schema:

    create_table "hotels", force: true do |t|
      t.spatial  "position", limit: {:srid=>4326, :type=>"point", :geographic=>true}
    end

model:

    class Hotel < ActiveRecord::Base
      set_rgeo_factory_for_column(:position, RGeo::Geographic.spherical_factory(:srid => 4326))

      def position=(params)
        inside_params = params || {}
        latitude  = inside_params["latitude"]
        longitude = inside_params["longitude"]
        super("POINT(#{longitude} #{latitude})")
      end
    end

and with this setting this used to work:

    Hotel.new(position: {"latitude" => 0, "longitude" => 0}).position.longitude

and return the correct value.

Currently, with just gems updated (rails, yours and globalize, which probably doesn't matter), this produces

    2.1.3p242 :004 > Hotel.new(position: {"latitude" => 0, "longitude" => 0}).position.longitude
    NoMethodError: undefined method `longitude' for #<RGeo::Cartesian::PointImpl:0xb96b44 "POINT (0.0 0.0)">

    2.1.3p242 :011 > Hotel.new(position: {"latitude" => 0, "longitude" => 0}).position.latitude
    NoMethodError: undefined method `latitude' for #<RGeo::Cartesian::PointImpl:0x2a85cd0 "POINT (0.0 0.0)">


Is this a regression, a bug? Can I help to fix it?

**Comment by teeparham** [comment]
This is helpful: http://technology.customink.com/blog/2015/01/06/activerecord-42s-type-casting/

**Comment by thibaudgg** [comment]
@teeparham Hey Tee, this particular issue is the last one that prevent us from upgrading our app to Rails 4.2..
Do you have an idea about when it'll be fixed/merged? Can we help you in anyway?
Thanks a lot for your work!

**Comment by teeparham** [comment]
This still doesn't work, but it's getting closer. Help is welcome. Checkout this branch & try to fix the broken tests if you want to help.

**Comment by thibaudgg** [comment]
@teeparham Thanks I'll try to have a look this week.
Do you know if the @seuros [fork](https://github.com/seuros/activerecord-postgis-adapter) works with 4.2?

**Comment by seuros** [comment]
@thibaudgg , Oh, i have this adapter working in one of my project (not in the fork).
I had removed the jruby support temporary, i will restore it and send a PR.

**Comment by thibaudgg** [comment]
@seuros great to hear, because the fork gives me that error: 
`uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::TableDefinition`. 

It would be awesome to have a new PR. Thanks!

**Comment by teeparham** [comment]
Todo:

In `OID::Spatial#parse_wkt`: 
* The SRID from the column is not used. It is available in the sql_type
* Need to retrieve the column factory from the parent column. The type class does not know the table nor column to which it belongs. So we need to pass more info to the type.

See https://github.com/rgeo/activerecord-postgis-adapter/blob/activerecord42/lib/active_record/connection_adapters/postgis_adapter/oid/spatial.rb#L67

T

**Comment by thibaudgg** [comment]
Awesome, thanks for your job. Your last commits already remove our type casting we got in our app. Looking forward for the new release!

**Comment by seuros** [comment]
@teeparham 
So i have started refactoring the working adapter to match your API, currently i have this
```ruby
  create_table :cities, force: true do |t|
    t.string :name
    t.text :long_name
    t.st_point 'latlon'
    t.st_point 'latlon3785', srid: 3785
    t.st_point 'latlon4326', geographic: true
    t.line_string 'path', srid: 3785
    t.st_polygon 'region', has_m: true, srid: 3785
    t.st_polygon 'province', has_m: true, srid: 3785
    t.st_point 'location'
    t.geometry 'geometry_shortcut'
    t.geometry 'geography_shortcut', geographic: true
  end
```

should we use st_* or geo_* , i used st_to match postgis, but i can change that. 
Also i'm not a fan of the limit hack ```limit:{has_m: true, srid: 3785}```

And since AR 4.x. we don't really need a t.spatial type we can use t.column :foo, :geometry

In my opinion, we could add helper for `geometryz` & `geometryzm`  & `geometrym`

Wdyt ?

**Comment by seuros** [comment]
cc @thibaudgg

**Comment by thibaudgg** [comment]
@seuros I think matching postsgis with `st_*` seems like a good idea. Thanks!

**Comment by averas** [comment]
Is this is known issue?

Could not log "sql.active_record" event. NoMethodError: private method `binary?' called for #<ActiveRecord::ConnectionAdapters::PostGISAdapter::OID::Spatial:0x000000088f3060>

**Comment by teeparham** [comment]
I like the idea of naming the point & polygon types as `st_point` and `st_polygon` rather than the `geo_` prefix. I'll make that change. ST is the PostGIS abbreviation for "spatial type".

cc @seuros

**Comment by thibaudgg** [comment]
:+1:

**Comment by plarson** [comment]
These changes got the tests working for me:

https://github.com/BurnThis/activerecord-postgis-adapter/commit/2402738fc80dde48aa09beb20f3621dd8686a010

**Comment by thibaudgg** [comment]
@plarson awesome news, thanks!

**Comment by teeparham** [comment]
@plarson thanks very much! I will cherry pick that commit onto this branch and push it soon.

**Comment by Neku** [comment]
Can't wait for this! Thank you very much guys.

**Comment by teeparham** [comment]
Tests are passing locally for me with ruby 2.1.5 (most of the time).

This is really close...

**Comment by thibaudgg** [comment]
@teeparham thanks a lot for the hard work, working great in our app! Do you plan a gem release soon? :heart_decoration:

**Comment by teeparham** [comment]
This branch is released as 3.0.0.beta1. Test with:

```ruby
gem "activerecord-postgis-adapter", "3.0.0.beta1"
```

Unless there are major problems, I will be merging this into master soon and releasing 3.0.0.

**Comment by thibaudgg** [comment]
`3.0.0.beta1` works great for us, thanks!

**Comment by andrewhao** [comment]
I'm unclear to the internals of this adapter, but I think something may be off here:

In a migration:

```ruby
class CreateTrackPoints < ActiveRecord::Migration
  def change
    create_table :track_points do |t|
      t.st_point :coordinate, geographic: true
    end
  end
end
```

Executing this writes out this into my `schema.rb`:

```ruby
create_table "track_points", force: :cascade do |t|
  t.geography "coordinate", limit: {:srid=>4326, :type=>"point", :geographic=>true}
end
```

That's fine and well, but any time I attempt to run any rake command involving `db:schema:load`, I get the following error:

```
/opt/rubies/2.2.0/bin/ruby -I/opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib:/opt/rubies/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-support-3.1.2/lib /opt/rubies/2.2.0/
lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb  --exclude-pattern spec/features/\*\*/\*_spec.rb
rake aborted!
ActiveRecord::StatementInvalid: PG::InvalidParameterValue: ERROR:  Invalid geometry type modifier: geography
LINE 1: ...ck_points" ("id" serial primary key, "coordinate" geometry(G...
                                                             ^
: CREATE TABLE "track_points" ("id" serial primary key, "coordinate" geometry(GEOGRAPHY,4326), "elevation" decimal, "heart_rate" integer, "time" timestamp, "track_id" integer)
/Users/andrewhao/workspace/velocitas-core/db/schema.rb:35:in `block in <top (required)>'
/Users/andrewhao/workspace/velocitas-core/db/schema.rb:14:in `<top (required)>'
-e:1:in `<main>'
PG::InvalidParameterValue: ERROR:  Invalid geometry type modifier: geography
LINE 1: ...ck_points" ("id" serial primary key, "coordinate" geometry(G...
                                                             ^
/Users/andrewhao/workspace/velocitas-core/db/schema.rb:35:in `block in <top (required)>'
/Users/andrewhao/workspace/velocitas-core/db/schema.rb:14:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:test:load_schema
(See full trace by running task with --trace)
```

Would it make sense to have the adapter write out the following statement instead into schema.rb?

```diff
```

Doing so seems to fix the problem.

**Comment by teeparham** [comment]
I'm merging this into master, although it's not quite ready for a 3.0.0 release yet. Please open bugs (like the one above) as individual issues.

**Comment by andrewhao** [comment]
Will do.

**Comment by erickreutz** [comment]
@averas I'm running into that same issue. Did you figure anything out for it?
